version: '2'
services:
    whatscover-app:
        image: whatscover
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://whatscover-mysql:3306/whatscover?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=whatscover-elasticsearch:9300
        ports:
            - 8080:8080
    whatscover-mysql:
        extends:
            file: mysql.yml
            service: whatscover-mysql
    whatscover-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: whatscover-elasticsearch
